# Generated by Django 4.0 on 2025-05-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='camada',
        ),
        migrations.AddField(
            model_name='camada',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camadas', to='web.curso'),
        ),
        migrations.AddField(
            model_name='camada',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='web.Estudiante'),
        ),
    ]
